overlay = "."
crate_src_path = ".."
maintainer = "Proxmox Support Team <support@proxmox.com>"
whitelist = [ "src/glue.c" ]

[source]
# TODO: update once public
vcs_git = ""
vcs_browser = ""

[packages.lib]
depends = [
  "libfuse3-dev",
]
